import asyncio
import time
import os
from unittest import runner
from google.adk.sessions import InMemorySessionService
from google.adk.runners import Runner
from google.genai import types as genai_types
#from agents.agent import create_root_agent
#from anamoly_agent.agent import root_agent
import sys
from os import path
sys.path.append( path.dirname( path.dirname( path.abspath(__file__) ) ) )

from anamoly_agent.agent import root_agent
from config.settings import APP_NAME_FOR_ADK, USER_ID, INITIAL_STATE, ADK_SESSION_KEY
import logging
from dotenv import load_dotenv
load_dotenv()
#import opik

session_service: InMemorySessionService = None
myrunner: Runner =  None
sessions = {}

def initialize():

    #opik.configure(use_local=False)
    logging.basicConfig(
    filename='app.log',  # Name of the log file
    level=logging.INFO,   # Minimum logging level to capture (e.g., INFO, DEBUG, WARNING, ERROR, CRITICAL)
    format='%(asctime)s - %(levelname)s - %(message)s', # Format of log messages
    filemode='a'          # 'a' for append (default), 'w' for overwrite
    )

    global session_service, myrunner

    session_service = InMemorySessionService() 

    myrunner = Runner( 
        agent=root_agent,
        app_name=APP_NAME_FOR_ADK,
        session_service=session_service
    )

async def create_session(session_id: str):
    # Create a new session in ADK's session service.
    global session_service
    #asyncio.run(
    await session_service.create_session(
        app_name=APP_NAME_FOR_ADK,
        user_id=USER_ID,
        session_id=session_id,
        state=INITIAL_STATE, # Initialize with predefined state.
    )
    #)

       
    

async def run_adk_async(session_id: str, user_message_text: str):
    global session_service, myrunner
    session = await myrunner.session_service.get_session(app_name=APP_NAME_FOR_ADK, user_id=USER_ID, session_id=session_id)
    if not session:
        return "Error: ADK session not found."
    
    # Prepare the user's message in the format expected by ADK/Gemini.
    content = genai_types.Content(role='user', parts=[genai_types.Part(text=user_message_text)])
    final_response_text = "[Agent encountered an issue]" # Default error message
    
    # Iterate through the asynchronous events generated by the ADK runner.
    # ADK can yield multiple events (e.g., tool calls, interim responses) before the final response.
    async for event in myrunner.run_async(user_id=USER_ID, session_id=session_id, new_message=content):
        logging.info(f"Event: {event}")
        if event.is_final_response(): # We are only interested in the final response from the agent.
            if event.content and event.content.parts and hasattr(event.content.parts[0], 'text'):
                final_response_text = event.content.parts[0].text
            break # Exit the loop once the final response is received.
    return final_response_text

# def run_adk_sync(session_id: str, user_message_text: str) -> str:
#     return asyncio.run(run_adk_async(session_id, user_message_text))

initialize()    

